name: Update USOM Blocklists

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Git kurulumu ve repo çekme
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout main

      - name: Python ve requests kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests

      - name: USOM verilerini çek ve dosyaları güncelle
        run: |
          cd repo
          python3 script.py

      - name: Güncellemeyi commit ve push et
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd repo
          git add Usom*.txt
          git commit -m "USOM blocklist updated" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
